### ISSUE TITLE
Make `substitue_current_word` public

### ISSUE THREAD

**Issue by Myzel394** [wassimk/scalpel.nvim#1]
Hey, I'd really love to use this plugin. However, I already got `<leader>e` set. [Automatically setting keymaps is generally discouraged](https://github.com/nvim-neorocks/nvim-best-practices?tab=readme-ov-file#keyboard-keymaps)

To be able to set custom keymaps, we need to make the function [`substitute_current_word`](https://github.com/wassimk/scalpel.nvim/blob/main/plugin/scalpel.lua#L53) public. Please return a module table in this file, so that we can set custom keymaps.

**Comment by wassimk** [comment]
Hi @Myzel394! Thanks for your issue. I just extracted this from my setup last weekend and am surprised it was found so quickly. I plan to modularize it for self-mapping and lazy loading, potentially finishing before I start work in an hour. Stand by!

**Comment by wassimk** [comment]
@Myzel394, it's ready to go, and I have updated the [README](https://github.com/wassimk/scalpel.nvim/blob/main/README.md) with the details.
